"""Output writer for draft reports."""

import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from ..config import Config
from ..models import DraftReport

logger = logging.getLogger(__name__)


def write_report(report: DraftReport, output_path: Optional[Path] = None) -> Path:
    """
    Write draft report to Markdown file.

    Args:
        report: DraftReport object
        output_path: Custom output path (uses default if None)

    Returns:
        Path to written file
    """
    if output_path is None:
        Config.OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        output_path = Config.OUTPUT_DIR / f"daily_drafts_{report.date}.md"

    logger.info(f"Writing report to {output_path}")

    content = _build_markdown(report)

    try:
        with open(output_path, "w") as f:
            f.write(content)

        logger.info(f"Successfully wrote report to {output_path}")
        return output_path

    except Exception as e:
        logger.error(f"Failed to write report: {e}")
        raise


def _build_markdown(report: DraftReport) -> str:
    """Build markdown content for report."""
    lines = []

    # Header
    lines.append(f"# InsightPress Daily Drafts - {report.date}")
    lines.append("")
    lines.append(f"*Generated: {report.timestamp}*")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Summary stats
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total items fetched:** {report.total_items_fetched}")
    lines.append(f"- **Duplicates removed:** {report.total_duplicates_removed}")
    lines.append(f"- **Draft posts generated:** {len(report.top_drafts)}")
    lines.append(f"- **Other candidates:** {len(report.other_candidates)}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Top drafts
    lines.append("## Top Drafts")
    lines.append("")
    lines.append("*Copy-paste ready X posts:*")
    lines.append("")

    for i, draft in enumerate(report.top_drafts, 1):
        lines.append(f"### Draft {i}")
        lines.append("")
        lines.append("```")
        lines.append(draft.content)
        lines.append("```")
        lines.append("")
        lines.append(f"**Source:** {draft.source_item.title}")
        lines.append(f"**Link:** {draft.source_item.url}")
        lines.append(f"**From:** {draft.source_item.source}")
        lines.append(f"**Published:** {draft.source_item.published_at.strftime('%Y-%m-%d %H:%M UTC')}")
        lines.append(f"**Character count:** {draft.char_count}/{Config.CHAR_LIMIT}")
        lines.append(f"**Generation mode:** [{draft.generation_mode}]")
        lines.append("")

    lines.append("---")
    lines.append("")

    # Other candidates
    if report.other_candidates:
        lines.append("## Other Good Candidates")
        lines.append("")
        lines.append("*Consider these for future posts:*")
        lines.append("")

        for i, ranked in enumerate(report.other_candidates, 1):
            item = ranked.item
            reasons = ", ".join(ranked.reasons) if ranked.reasons else "No specific reasons"

            lines.append(f"{i}. **{item.title}**")
            lines.append(f"   - Source: {item.source}")
            lines.append(f"   - Score: {ranked.score:.2f}")
            lines.append(f"   - Reasons: {reasons}")
            lines.append(f"   - Link: {item.url}")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Skipped/duplicates
    if report.skipped_items:
        lines.append("## Skipped / Duplicates")
        lines.append("")
        lines.append(f"*{len(report.skipped_items)} items removed during deduplication:*")
        lines.append("")

        # Only show first 20 to avoid cluttering
        for title, reason in report.skipped_items[:20]:
            lines.append(f"- {title[:80]}{'...' if len(title) > 80 else ''}")
            lines.append(f"  *{reason}*")
            lines.append("")

        if len(report.skipped_items) > 20:
            lines.append(f"*...and {len(report.skipped_items) - 20} more*")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by [InsightPress](https://github.com/yourusername/insightpress) - Draft X posts from trusted tech/AI sources*")
    lines.append("")

    return "\n".join(lines)
